######################### python train_stationary.py -e fixed_utdrl -s 770
# Model Configurations  #
#########################

# ROOT: '/home/lidwh/CaRiNG/caring/datasets/ug_tdmp'
# LOG: '/home/lidwh/CaRiNG/log'
# DATASET: 'ug_tdmp'

ROOT: '/home/lidwh/CaRiNG/datasets_missing/seed770_mixinglag1'
LOG: '/home/lidwh/CaRiNG/log_missing'
# DATASET: 'missing'

  
VAE:
    GPU: [1]
    CPU: 4
    TRAIN_BS: 64
    VAL_BS: 64
    EPOCHS: 50
    N_VAL_SAMPLES: 1024
    LAG: 1
    LENGTH: 9
    TRANS_PRIOR: 'NP'
    LR: 1.0e-3
    BETA: 3.0e-3
    GAMMA: 1.0e-1
    INPUT_DIM: 3
    LATENT_DIM: 3
    BIAS: FALSE
    ENC:
        HIDDEN_DIM: 128
        SIDE_TRUEZ: 0
        # """4 for CaRiNG, 0 for mine and TDRL"""
        # SIDE_TRUEX: 4
        SIDE_TRUEX: 0
    DEC:
        HIDDEN_DIM: 128
        DIST: 'gaussian'
        SIDE_TRUEZ: 0
        SIDE_HATZ: 0
        SIDE_TRUEX: 0
    PIN: TRUE
    

MCC:
    FREQ: 0.1
    CORR: 'Pearson' # 'Spearman'